### ISSUE TITLE
can't download album

### ISSUE THREAD

**Issue by driver768** [tomleb/proxy-for-immich#13]
Hi, getting this error when trying to download full album:

![Screenshot_3](https://github.com/user-attachments/assets/b8f2c6ef-ddd6-453c-8d84-1d86d7439e94)

Header shows: Status Code 400 Bad Request

{
  "message": "assetIds, albumId, or userId is required",
  "error": "Bad Request",
  "statusCode": 400,
  "correlationId": "3got4dje"
}

Downloading separate photos works.

**Comment by tomleb** [comment]
Ah that's a bummer. I'm thinking one of the changes in v0.5.0 or v0.6.0 might have caused this. If you downgrade prozy-for-immich, does it work for you?

I'll be without a computer for a little bit so my ability to debug will be pretty limited. Apologies for this, I hope to add some more testing soon to prevent regressions.

**Comment by tomleb** [comment]
Ah seems like github auto closes issues.. 

I was able to revert the header whitelist change from v0.5.0 and created a new v0.7.0 tag. I'll be revisiting this later so that I can still whitelist headers without brealing download. Feel free to re-open if it isn't fixed for you!

**Comment by driver768** [comment]
It seems to be working, thanks for quick fix 👍
